seed: 2024

model:
    name: "WaveNet"
    n_layers: 10
    n_channels: 64
    window_size: 384 # equals to 4-day data (4 * 24 * 4)
    horizon: 96 # equals to 1-day data (1 * 24 * 4)
    
training:
    n_epochs: 30
    reg_coeff: 0.15
    batch_size: 32
    learning_rate: 0.0005755409728408005
    lr_decay: 0.9071579292109428 # used for exponential scheduler
    target_idx: 1200 # For Windo Offshore is 1200
    log_interval: 100 # log average losses every N gradient updates
    save_interval: 1000 # save model every N gradient updates
    validate_every_n_updates: 2000 # validate model every N gradient updates

paths:
    data_dir: "/home/martius-lab/Desktop/renewable_ml/data/"
    results_dir: "/home/martius-lab/Desktop/renewable_ml/results/wind_offshore/"

    
    