seed: 2024

model:
    name: "WaveNet"
    n_layers: 10
    n_channels: 128
    window_size: 192 # equals to 2-day data (2 * 24 * 4)
    horizon: 96 # equals to 1-day data (1 * 24 * 4)
    
training:
    n_epochs: 30
    reg_coeff: 0.1
    batch_size: 64
    learning_rate: 0.0002182186105965356
    lr_decay: 0.8156999529192888 # used for exponential scheduler
    target_idx: 1201 # For Windo Onshore is 1201
    log_interval: 100 # log average losses every N gradient updates
    save_interval: 1000 # save model every N gradient updates
    validate_every_n_updates: 2000 # validate model every N gradient updates

paths:
    data_dir: "/home/martius-lab/Desktop/renewable_ml/data/"
    results_dir: "/home/martius-lab/Desktop/renewable_ml/results/wind_onshore/"

    
    